# frozen_string_literal: true

require 'test_helper'

class PasswordMailerTest < ActionMailer::TestCase
  test 'reset link email' do
    user = users(:one)
    user.password = 'password123'
    user.save!

    email = PasswordMailer.reset_link(user)

    assert_emails 1 do
      email.deliver_now
    end

    assert_equal [user.email], email.to
    assert_equal 'Reset your Spanner password', email.subject
    # The reset URL contains a signed token generated by has_secure_password
    assert_match %r{/reset-password/[A-Za-z0-9_-]+}, email.body.encoded
  end
end
