# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a7b4339a6694c8129b2dd396738a042759983b11b90723421bad85310c1ba453ee78b51e185e9cdd85859491bb5f9b893ed2c870d924c18fda860df0d976b4e

test:
  secret_key_base: 1fb3fd4976802361086789ffc114a7bb4b9e766423257a07e7598c052016177e6abeefb7d68537f53dfc313d3025265a8329a77af85492d660650bb26db26131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
