---
name: Boat
distance_unit:
  - nmi
items:
  - name: Oil Change
    keywords:
      - oil change
      - engine oil
      - motor oil
      - oil filter
    context:
      - engine
      - motor
    intervals:
      mo: 12
  - name: Hull Cleaning
    keywords:
      - hull cleaning
      - clean hull
      - hull wash
      - bottom cleaning
    intervals:
      mo: 12
  - name: Zinc Replacement
    keywords:
      - zinc replacement
      - replace zinc
      - zinc anode
      - anode replacement
    intervals:
      mo: 12
  - name: Impelor Service
    keywords:
      - impeller service
      - replace impeller
      - impeller replacement
      - water pump impeller
    intervals:
      mo: 24
  - name: Fuel Filter
    keywords:
      - fuel filter
      - replace fuel filter
      - fuel filter replacement
    intervals:
      mo: 12
  - name: Battery
    keywords:
      - new battery
      - replace battery
      - battery replacement
      - battery died
      - battery dead
    intervals:
      mo: 48
  - name: Antifreeze / Cooling System
    keywords:
      - coolant
      - antifreeze
      - radiator fluid
      - coolant flush
    intervals:
      mo: 24
  - name: Bilge Pump Check
    keywords:
      - bilge pump
      - bilge pump check
      - bilge pump service
    intervals:
      mo: 12
  - name: Safety Gear Check
    keywords:
      - safety gear
      - safety equipment
      - safety check
      - safety inspection
    intervals:
      mo: 12
