---
name: RV
distance_unit:
- mi
items:
- name: Oil Change
  keywords:
  - oil change
  - engine oil
  - motor oil
  - oil filter
  context:
  - engine
  - motor
  intervals:
    mi: 5000
    mo: 12
- name: Generator Service
  keywords:
  - generator service
  - generator maintenance
  - service generator
  intervals:
    mo: 12
- name: Propane System Check
  keywords:
  - propane system
  - propane check
  - propane inspection
  - lp system
  intervals:
    mo: 12
- name: Roof Inspection
  keywords:
  - roof inspection
  - inspect roof
  - roof check
  - roof seal
  intervals:
    mo: 6
- name: Battery
  keywords:
  - new battery
  - replace battery
  - battery replacement
  - battery died
  - battery dead
  intervals:
    mo: 60
- name: Tire Inspection
  keywords:
  - tire inspection
  - inspect tire
  - tire check
  - tire condition
  intervals:
    mo: 12
- name: Transmission Fluid
  keywords:
  - transmission fluid
  - transmission oil
  - gearbox oil
  - transmission service
  - transmission flush
  context:
  - transmission
  - gearbox
  intervals:
    mi: 30000
- name: Air Filter
  keywords:
  - air filter
  - engine air filter
  intervals:
    mi: 15000
