plugins: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/migrate/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 160
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
    - "lib/tasks/*.rake"
  Max: 30

Rails/I18nLocaleTexts:
  Enabled: false

Rails/StrongParametersExpect:
  Enabled: false
