# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.0'
# Use postgresql as the database for Active Record
gem 'bcrypt', '~> 3.1'
gem 'pg', '~> 1.5'
gem 'rack-attack', '~> 6.6'
# Use Puma as the app server
gem 'puma'

gem 'active_model_serializers'
gem 'aws-sdk-s3', '~> 1.0', require: false
gem 'base64'
gem 'benchmark'
gem 'bigdecimal'
gem 'browser'
gem 'csv'
gem 'fiddle'
gem 'mutex_m'
gem 'ostruct'
gem 'postmark-rails'
gem 'premailer-rails'
gem 'queue_classic', '>= 4.0.0'
gem 'rufus-scheduler', '~> 3.9'
gem 'schema2type'
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'stemmer', '~> 1.0'
gem 'virtus'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem 'dotenv-rails'
  gem 'listen', '~> 3.7'
  gem 'rubocop'
  gem 'rubocop-rails'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'webmock'
end

# Include timezone data for all platforms (required for Railway)
gem 'tzinfo-data'
